### ISSUE TITLE
Assignment-8 :

### ISSUE THREAD

**Issue by 53bit23** [vtcbca/basic-programming-46bit23#2]
What type of loop is used to create rows?

**Comment by 53bit23** [comment]
A for loop is used to iterate over each row.

**Comment by 46bit23** [comment]
A for loop is used to iterate over each row.

**Comment by 53bit23** [comment]
What data type is used for the input value n?

**Comment by 46bit23** [comment]
The input n is an integer (int).

**Comment by 53bit23** [comment]
Can this program be modified to print numbers instead of letters?

**Comment by 53bit23** [comment]
Yes, by directly printing numbers instead of using chr().

**Comment by 46bit23** [comment]
Yes, by directly printing numbers instead of using chr().

**Comment by 53bit23** [comment]
What happens if you remove the spaces in the pattern?

**Comment by 46bit23** [comment]
The triangle shape will become distorted, as all rows will align to the left.

**Comment by 53bit23** [comment]
How do you test the program for different patterns?

**Comment by 46bit23** [comment]
Change the value of n or modify the logic for rows and characters.
